# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - id: kreaper
    binary: kreaper
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - builds:
      - kreaper
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - ids:
      - kreaper
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    image_templates:
      - ghcr.io/baez90/kreaper:{{ .Version }}-amd64
      - ghcr.io/baez90/kreaper:{{ .Major }}-amd64
    dockerfile: deployments/Dockerfile
  - ids:
      - kreaper
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    image_templates:
      - ghcr.io/baez90/kreaper:{{ .Version }}-arm64v8
      - ghcr.io/baez90/kreaper:{{ .Major }}-arm64v8
    dockerfile: deployments/Dockerfile

docker_manifests:
  - name_template: ghcr.io/baez90/kreaper:{{ .Version }}
    image_templates:
      - ghcr.io/baez90/kreaper:{{ .Version }}-amd64
      - ghcr.io/baez90/kreaper:{{ .Version }}-arm64v8
  - name_template: ghcr.io/baez90/kreaper:{{ .Major }}
    image_templates:
      - ghcr.io/baez90/kreaper:{{ .Major }}-amd64
      - ghcr.io/baez90/kreaper:{{ .Major }}-arm64v8