# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - id: kreaper
    binary: kreaper
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - builds:
      - kreaper
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - ids:
      - kreaper
    image_templates:
      - ghcr.io/baez90/kreaper:latest
      - ghcr.io/baez90/kreaper:{{ .Tag }}
      - ghcr.io/baez90/kreaper:{{ .Major }}
      - ghcr.io/baez90/kreaper:{{ .ShortCommit}}
    dockerfile: deployments/Dockerfile
